name: Eleventy Build
	
on: 
  push:
  
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js environment
	uses: actions/setup-node@v4.0.2 
	with:
	  node-version: '20'
      # - name: Build
      #   uses: TartanLlama/actions-eleventy@master
      #   with:
      #     install_dependencies: true
      - run: npm install
      - run: npm run build
      - name: Deploy
	uses: peaceiris/actions-gh-pages@v4.0.0
	with:
	          publish_dir: _site 
	          publish_branch: gh-pages
	          github_token: ${{ secrets.DEPLOY_TOKEN }}
